Models/Curso.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
namespace tarea_12082023_jesus_soria.Models {
    public enum Curso {

        [Display(Name = "Matemática")]
        MATEMATICA, 
        
        [Display(Name = "Lenguaje")]
        LENGUAJE, 
        
        [Display(Name = "Física")]
        FISICA
    }
}

Models/ErrorViewModel.cs
namespace tarea_12082023_jesus_soria.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Estudiante.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace tarea_12082023_jesus_soria.Models {
    [Serializable]
    public class Estudiante {
    
        [Required(ErrorMessage = "Debe escribir el nombre")]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; }

        [Display(Name = "Apellido Paterno")]
        public string Apellido_Paterno { get; set; }

        [Display(Name = "Apellido Materno")]
        public string Apellido_Materno { get; set; }

        [Display(Name = "Genero")]
        public Genero Genero { get; set; }

        [Display(Name = "Curso")]
        public Curso Curso { get; set; }

        public string Registrar() {
            double costoCredito = 250; // Costo de cada crédito
            double costoTotal = 0;

            if (!string.IsNullOrEmpty(Nombre)) {
                if (!string.IsNullOrEmpty(Apellido_Paterno)) {
                    if (!string.IsNullOrEmpty(Apellido_Materno)) {
                        switch (Curso) {
                            case Curso.MATEMATICA:
                                costoTotal = 3 * costoCredito;
                                break;
                            case Curso.LENGUAJE:
                                costoTotal = 1 * costoCredito;
                                break;
                            case Curso.FISICA:
                                costoTotal = 2 * costoCredito;
                                break;
                        }

                        return "Estudiante: " + Nombre + 
                            " " + Apellido_Paterno + 
                            " " + Apellido_Materno +
                            "\nGénero: " + Genero +
                            "\nCurso: " + Curso +
                            "\nCosto Total del Curso: " + costoTotal.ToString("C"); // Formato de moneda
                    } else {
                        throw new ArgumentException("No ingresó el apellido materno");
                    }
                } else {
                throw new ArgumentException("No ingresó el apellido paterno");     
                }
            } else {
                throw new ArgumentException("No ingresó el nombre");       
            }
        }
    }
}

Models/Genero.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
namespace tarea_12082023_jesus_soria.Models {
    public enum Genero {
        [Display(Name = "Masculino")]
        Masculino, 
        
        [Display(Name = "Femenino")]
        Femenino
    }
}

Controllers/EstudianteController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using tarea_12082023_jesus_soria.Models;
namespace tarea_12082023_jesus_soria.Controllers {

    public class EstudianteController : Controller {
        private readonly ILogger<EstudianteController> _logger;

        private List<Estudiante> listaEstudiantes = new List<Estudiante>();

        public EstudianteController(ILogger<EstudianteController> logger) {
            _logger = logger;
        }


   
      
        
        // VISTA DEL FORMULARIO PARA EL ESTUDIANTE
        public IActionResult Form_estudiante() {
            return View();
        }


         // METODO POST PARA REGISTRAR EL ESTUDIANTE
        [HttpPost]
        public IActionResult Registrar(Estudiante objEstudiante) {
            string respuesta;

            try{
                 respuesta = objEstudiante.Registrar()+"";
        
            }catch(Exception ex){
                 respuesta = ex.Message;
            }
            ViewData["Message"] = respuesta;
            return View("Form_estudiante"); 
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View("Error!");
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using tarea_12082023_jesus_soria.Models;

namespace tarea_12082023_jesus_soria.Controllers;

public class HomeController : Controller {
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger) {
        _logger = logger;
    }

    public IActionResult Index() {
        return View();
    }

    public IActionResult Privacy() {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error() {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Estudiante/Form_estudiante.cshtml
@{
    ViewData["Title"] = "Formulario";
}

@model tarea_12082023_jesus_soria.Models.Estudiante
<center><h1>Registrar Estudiante</h1></center>
<br>

<div class="text-center">
    <form asp-controller="Estudiante" asp-action="Registrar" method="post" onsubmit="return validarFormulario();">
        <div class="form-group">
            <div class="row">
                <label asp-for="Nombre" class="col-lg-2"></label>
                <input type="text" asp-for="Nombre" class="col-lg-2">
            </div> 

            <div class="row">
                <label asp-for="Apellido_Paterno" class="col-lg-2"></label>
                <input type="text" asp-for="Apellido_Paterno" class="col-lg-2">
            </div> 

            <div class="row">
                <label asp-for="Apellido_Materno" class="col-lg-2"></label>
                <input type="text" asp-for="Apellido_Materno" class="col-lg-2">
            </div> 

            <div class="row">
                <label asp-for="Genero" class="col-lg-2"></label>
                <select asp-for="Genero" class="col-lg-2" asp-items="Html.GetEnumSelectList<Genero>()">
                    <option selected = "selected" value="">Seleccione</option>
                </select>
            </div>

            <div class="row">
                <label asp-for="Curso" class="col-lg-2"></label>
                <select asp-for="Curso" class="col-lg-2" asp-items="Html.GetEnumSelectList<Curso>()">
                    <option selected = "selected" value="">Seleccione</option>
                </select>
            </div><br>

            <div class="row">
                <input type="submit" value="Registrar" class="col-lg-2 custom-button orange-button">
                <input type="button" value="Limpiar" class="col-lg-2 custom-button red-button" onclick="limpiarCampos()">
            </div>
        </div>
    </form>
    <div id = "messageDiv">
        <h1>@ViewData["Message"]</h1>
    </div>
</div>

<script>
    function limpiarCampos() {
        document.getElementById("Nombre").value = "";
        document.getElementById("Apellido_Paterno").value = "";
        document.getElementById("Apellido_Materno").value = "";
        document.getElementById("Genero").selectedIndex = 0; // Seleccione la primera opción
        document.getElementById("Curso").selectedIndex = 0; // Seleccione la primera opción

        // Limpiar el ViewData
        document.getElementById("messageDiv").innerText = "";

        return false; // Necesario para evitar que el formulario se envíe
    }
</script>

<script>
    function validarFormulario() {
        var generoSeleccionado = document.getElementById("Genero").value;
        var cursoSeleccionado = document.getElementById("Curso").value;
        
        /*if (generoSeleccionado === "" || cursoSeleccionado === "") {
            alert("Por favor, seleccione una opción válida para Género y Curso.");
            return false;
        }*/

        if (generoSeleccionado === "") {
            alert("Por favor, seleccione una opción válida para Género.");
            return false;
        }

        if (cursoSeleccionado === "") {
            alert("Por favor, seleccione una opción válida para Curso.");
            return false;
        }
        return true;
    }
</script>

<style>
   .custom-button {
        margin-right: 10px; /* Agrega un espacio a la derecha de los botones */
    }

    .orange-button {
        background-color: orange;
    }

    .red-button {
        background-color: white;
    } 
    
</style>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - tarea_12082023_jesus_soria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/tarea_12082023_jesus_soria.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">tarea_12082023_jesus_soria</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estudiante" asp-action="Form_estudiante">Formulario Estudiante</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - tarea_12082023_jesus_soria - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>